baseurl: "https://joshix.com/"
title: joshix.com
theme: ghostwriter
languageCode: en-us
copyright: Joshua Wood
disqusShortname: XXX
googleAnalytics: G-483LEEM9XS
pygmentsUseClasses: true
pygmentsCodefences: true

# goldmark stanza need live only long enough to convert all inline html brought
# over from previous incarnations of the site.
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

taxonomies:
  tag: tags

params:
# author.name set to Joshix (instead of Josh Wood) is a hack for the ghostwriter
# theme, which takes Site.Author.name (instead of eg Site.title) as the second
# part of <title> elements.
  author:
    name: Joshix
    profile: "https://joshix.com"
  mainSections:
    - post
  intro: true
  headline: ""
  description: ""
  # Navigation square social icons config. Used in partials/header.html. Icons
  # in CSS classes from https://fontawesome.com/v4.7.0/icons/#web-application
  #twitter: "https://twitter.com/joshixisjosh9"
  #facebook: "https://www.facebook.com/username"
  #gitlab: "https://gitlab.com/XXX"
  github: "https://github.com/joshix"
  #stackoverflow: "https://stackoverflow.com/users/9604749/josh-wood"
  linkedin: "https://linkedin.com/in/joshix/"
  email: j@joshix.com
  # END social icons config
  opengraph: true
  # `shareScv` determines what social share action buttons are shown on single
  # view of item of type post. In theme's partials/post-footer.html.
  shareTwitter: false
  shareFacebook: false
  shareGooglePlus: false
  shareLinkedIn: false
  # END social share action config
  dateFormat: "January 2, 2006"
  readingTime: false
  readingTimeText: "Estimated reading time:"

permalinks:
  post: "/:year/:month/:day/:filename/"
  page: "/:filename/"
#  presentation: "/presentation/:filename/"
