baseurl = "https://joshix.com/"
languageCode = "en-us"
title = "Josh Wood"
#author = "Josh Wood"
copyright = "Josh Wood. All rights reserved."
canonifyurls = true
paginate = 10
metaDataFormat = "yaml"
theme = "ghostwriter"

#disqusShortname = "joshix"
googleAnalytics = "UA-79186834-1"

#[[menu.main]]
    # name = "TAGS"
    # pre = "<i class='fa fa-tags'></i>"
    # weight = -110
    # identifier = "tags"
    # url = "/tags/"

[[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "projects"
    url = "/projects/"

#[[menu.footer]]
#    name = "LICENSE"
#    weight = -120
#    identifier = "license"
#    url = "/license/"

[permalinks]
# While we could declare a 'slug' in each document's metadata,
# ':filename' lets us name things as a matter of course, and yields a
# file hierarchy that more or less matches the httpd URL name space.
    post = "/:year/:month/:day/:filename/"
#    code = "/p/:slug/"
    page = "/:filename/"

[author]
    name = "Josh Wood"
    email = "j@joshix.com"

[params.widgets]
  recent_articles = true
  categories = false
  tags = false
  tag_cloud = true

[params]
  brand = "Jx%"
  footline = "Izena duen guzia omen da"
  topline = "rktship"
  mainSections = ["post"]

  # Text for the top menu link, which goes the root URL for the site.
  # Default (if omitted) is "Home".
#  home = "home"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "default"

# Sidebar social links.
  github = "https://github.com/joshix" # Your Github profile ID
  bitbucket = "" # Your Bitbucket profile ID
#  linkedin = "joshua-wood-a453aa90" # Your LinkedIn profile ID (from public URL)
  googleplus = "JoshuaWoodOrJoshix" # Your Google+ profile ID
  facebook = "" # Your Facebook profile ID
  twitter = "https://twitter.com/joshixisjosh9" # Your Twitter profile ID
  youtube = ""  # Your Youtube channel ID
  flattr = ""  # populate with your flattr uid

[blackfriday]
  angledQuotes = false
  fractions = true
  hrefTargetBlank = false
  latexDashes = true
  plainIdAnchors = true
  extensions = []
  extensionmask = []
