baseurl: "https://joshix.com/"
title: joshix.com
theme: ghostwriter
languageCode: en-us
copyright: Joshua Wood
disqusShortname: XXX
googleAnalytics: UA-79186834-1
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Josh Wood
  profile: "https://joshix.com"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: The Eclectilepsy
  description: ""
  twitter: "https://twitter.com/joshixisjosh9"
  #facebook: "https://www.facebook.com/username"
  #gitlab: "https://gitlab.com/XXX"
  github: "https://github.com/joshix"
  speakerdeck: "https://speakerdeck.com/joshix"
  stackoverflow: "https://stackoverflow.com/users/9604749/josh-wood"
  linkedin: "https://linkedin.com/in/joshix/"
  email: j@joshix.com
  opengraph: true
  shareTwitter: false
  shareFacebook: false
  shareGooglePlus: false
  shareLinkedIn: false
  dateFormat: "January 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: false
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"
  page: "/:filename/"

menu:
  main:
    - name: Blog
      url: /post/
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2
    # - name: Contact
    #   url: /page/contact/
    #   weight: 3
    # - name: About
    #   url: /page/about/
    #   weight: 4
