baseurl = "http://core-ch1a.local/"
languageCode = "en-us"

# Site title
title = "Jx%"

# Copyright
copyright = "(c) 2016 Josh Wood."

# Language
#languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
#metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "bootstrap"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = ""

[permalinks]
    post = "/blog/:year/:month/:slug/"
#    code = "/p/:slug/"
    page = "/:title/"

[taxonomies]
    tag = "tags"
    topic = "topics"
    category = "categories"

[author]
    name = "Josh Wood"
    email = "j@joshix.com"

#
# Optional parameters.
#
[params]
    # You can use markdown here.
    brand = "foobar"
    #topline = "Izena duen guzia omen da"
    #footline = "code with <i class='fa fa-heart'></i>"
    footline = "*Izena duen guzia omen da*"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "joshix" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "JoshuaWoodOrJoshix" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "joshixisjosh9" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
