baseurl = "http://core-ch1a.local"
languageCode = "en-us"
title = "Jx%"
theme = "bootie-docs"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/blog/:title/"

[params]

	sidebartitle = "Jx%"
	sidebartagline = "Tag test this"
	sidebarphoto = ""

	name = "Josh Wood"
	description = "Describe your website"
	bio = "Man about machines"
	# Enter optionally your twitter account
	twitter = "joshixisjosh9"
	enableRSS = true

	# The variables below are optional and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "/about"
	projects = "/projects"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Enjoys photographing polydactyl cats and writing short autobiographies"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
#    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
